const messages = {
  en: {
    message: {
      name: 'Name',
      modify: 'Modify',
      yes: 'Yes',
      no: 'No',
      home: 'Home',
      admin: 'Administrator ',
      visitor: 'Visitor',
      provider: 'Provider',
      providers: 'Providers',
      activity: 'Activity',
      activities: 'Activities',
      seeMap: 'See map',
      goToPage: 'Go to page',
      clear: 'Clear',
      keywordSearch: 'Keyword Search',
      registerAsProvider: 'Register as provider',
      providerName: 'Name of provider',
      cancel: 'Cancel',
      send: 'Send',
      save: 'Save',
      preview: 'Preview',
      fillAllFields: 'Please fill in all the fields',
      contactProvider: 'Contact a provider',
      login: 'Log in',
      logout: 'Log out',
      loginAs: 'Login as :',
      whoAreWe: 'Who are we ?',
      noNewMessage: 'No new message',
      modifyPresentationText: 'Modify the small presentation text',
      modifyPresentationTextBig: 'Modify the long presentation text',
      administerTheEvent: 'Administer the event',
      interactiveMap: 'Interactive map',
      manageProviderRequests: 'Manage provider requests',
      statistics: 'Statistics',
      providerDashboard: 'Provider dashboard',
      homePagePreview: 'Home page preview',
      noLocationSelected: 'No location selected',
      characteristicsOfTheSelectedLocation: 'Characteristics of the selected location',
      characteristicsOfTheLocation: 'Characteristics of the location',
      water: 'Water',
      electricity: 'Electricity',
      alreadyReservedSpot: 'Your activity already has a reserved spot',
      requestAlreadyRegistered: 'Request already registered',
      locationAlreadyReserved: 'Location already reserved',
      clickOnLocation: 'Click on a location on the map to select it',
      selectedLocation: 'Location {id} selected',
      manuallyChoose: 'Manually choose',
      locationAlreadyReservedTo: 'Location already reserved to the activity',
      deselect: 'Deselect',
      requestLocation: 'Request location',
      available: 'Available',
      pendingRequest: 'Pending request',
      occupied: 'Occupied',
      yourLocation: 'Your location',
      appearanceOfThePage: 'Appearance of the page',
      chooseServices: 'Choose services',
      seeStatistics: 'See statistics',
      choiceOfLocation: 'Choice of location',
      configurationOfTheActivity: 'Configuration of the activity',
      enableRegistration: 'Enable registration',
      signUp: 'Sign up',
      newProviders: 'New providers',
      adminPage: 'Administrator page',
      giveFeedback: 'Give a feedback',
      addActivity: 'Add activity',
      noActivityFound: 'No activities found',
      loadingPlsWait: 'Loading data. Please wait...',
      noNewRequest: 'No new request',
      satisfactionForm: 'Satisfaction form',
      receiveFeedback: 'Receive feedback',
      feedbackMessages: 'Feedback messages',
      replyToFeedback: 'Reply to feedback',
      organisation: 'Organisation',
      animations: 'Animations',
      accessibility: 'Accessibility',
      followedActivities: 'Followed activities',
      comment: 'Comment',
      reply: 'Reply',
      globalRating: 'Global rating',
      wouldRecommend: 'Would you recommend this event?',
      maybe: 'Maybe',
      whichActivities: 'Which activities did you attend? (check all that apply)',
      commentSuggestions: 'Comments / Suggestions',
      nameOptional: 'Name (optional)',
      emailOptional: 'Email (optional)',
      consentText: 'I agree that my responses may be used (anonymized) *',
      thankYouMessage: 'Thank you — your feedback helps us improve the event.',
    },
    'Formulaire de satisfaction': 'Satisfaction form',
    'Reception des avis': 'Receive feedback',
    'Messages des avis': 'Feedback messages',
    'Repondre à l\'avis': 'Reply to feedback',
    'Organisation': 'Organisation',
    'Animations': 'Animations',
    'Accesibilité': 'Accessibility',
    'Activités suivies': 'Followed activities',
    'Commentaire': 'Comment',
    'Répondre': 'Reply',
    'Oui': 'Yes',
    'Non': 'No',
    'maybe': 'Maybe',
    'Peut-être': 'Maybe',

  },
  fr: {
    message: {
      name: 'Nom',
      modify: 'Modifier',
      yes: 'Oui',
      no: 'Non',
      home: 'Accueil',
      admin: 'Administrateur',
      visitor: 'Visiteur',
      provider: 'Prestataire',
      providers: 'Prestataires',
      activity: 'Activité',
      activities: 'Activités',
      seeMap: 'Voir la carte',
      goToPage: 'Voir la page',
      clear: 'Effacer',
      keywordSearch: 'Recherche par mot-clé',
      registerAsProvider: "S'enregistrer en tant que prestataire",
      providerName: 'Nom du prestataire',
      cancel: 'Annuler',
      send: 'Envoyer',
      save: 'Sauvegarder',
      preview: 'Aperçu',
      fillAllFields: 'Veuillez remplir tous les champs',
      contactProvider: ' Contacter un prestataire',
      login: 'Se connecter',
      logout: 'Se déconnecter',
      loginAs: 'Se connecter en tant que :',
      whoAreWe: 'Qui sommes-nous ?',
      noNewMessage: 'Pas de nouveau message',
      modifyPresentationText: "Modifier le petit texte de présentation de l'évenement",
      modifyPresentationTextBig: "Modifier le long texte de présentation de l'évenement",
      administerTheEvent: 'Gérer la manifestation',
      interactiveMap: 'Carte interactive',
      manageProviderRequests: 'Gerer les demandes de prestataires',
      statistics: 'Statistiques',
      providerDashboard: 'Espace prestataire',
      homePagePreview: 'Apercu page de présentation',
      noLocationSelected: 'Aucun emplacement sélectionné',
      characteristicsOfTheSelectedLocation: "Caractéristiques de l'emplacement sélectionné",
      characteristicsOfTheLocation: "Caractéristiques de l'emplacement",
      water: 'Eau',
      electricity: 'Electricité',
      alreadyReservedSpot: 'Votre activité a déjà une place réservée',
      requestAlreadyRegistered: 'Demande déjà enregistrée',
      locationAlreadyReserved: 'Emplacement déjà réservé',
      clickOnLocation: 'Cliquez sur un emplacement sur la carte pour le sélectionner',
      selectedLocation: 'Emplacement {id} sélectionné',
      manuallyChoose: 'Choisir manuellement',
      locationAlreadyReservedTo: "Cet emplacement est déjà assigné à l'activité",
      deselect: 'Désélectionner',
      requestLocation: "Demander l'emplacement",
      available: 'Libre',
      pendingRequest: 'Demande en attente',
      occupied: 'Occupé',
      yourLocation: 'Votre emplacement',
      appearanceOfThePage: 'Apparence de la page',
      chooseServices: 'Choix des services',
      seeStatistics: 'Voir les statistiques',
      choiceOfLocation: "Choix de l'emplacement",
      configurationOfTheActivity: "Configuration de l'activité",
      enableRegistration: "Activer l'inscription",
      signUp: "S'inscire",
      newProviders: 'Nouveau prestataires',
      adminPage: 'Page administrateur',
      giveFeedback: 'Donner mon avis',
      addActivity: 'Ajouter une activité',
      noActivityFound: 'Aucune activité',
      loadingPlsWait: 'Chargement, veuiller patienter ...',
      noNewRequest: 'Pas de nouvelles demandes',
      satisfactionForm: 'Formulaire de satisfaction',
      receiveFeedback: 'Réception des avis',
      feedbackMessages: 'Messages des avis',
      replyToFeedback: 'Répondre à l\'avis',
      organisation: 'Organisation',
      animations: 'Animations',
      accessibility: 'Accessibilité',
      followedActivities: 'Activités suivies',
      comment: 'Commentaire',
      reply: 'Répondre',
      globalRating: 'Note globale',
      wouldRecommend: 'Recommanderiez-vous l\'évènement ?',
      maybe: 'Peut-être',
      whichActivities: 'Quelles activités avez-vous suivies ? (cochez)',
      commentSuggestions: 'Commentaire / Suggestions',
      nameOptional: 'Nom (optionnel)',
      emailOptional: 'Email (optionnel)',
      consentText: 'J\'accepte que mes réponses soient utilisées (anonymisées) *',
      thankYouMessage: 'Merci — vos retours nous aident à améliorer l\'événement.',

    },
    'Formulaire de satisfaction': 'Formulaire de satisfaction',
    'Reception des avis': 'Réception des avis',
    'Messages des avis': 'Messages des avis',
    'Repondre à l\'avis': 'Répondre à l\'avis',
    'Organisation': 'Organisation',
    'Animations': 'Animations',
    'Accesibilité': 'Accessibilité',
    'Activités suivies': 'Activités suivies',
    'Commentaire': 'Commentaire',
    'Répondre': 'Répondre',
    'Oui': 'Oui',
    'Non': 'Non',
    'Peut-être': 'Peut-être',
    'maybe':'Peut-être',

  },
}

export { messages }
