const messages = {
  en: {
    message: {
      home: 'Home',
      admin: 'Administrator ',
      provider: 'Provider',
      providers: 'Providers',
      activity: 'Activity',
      seeMap: 'See map',
      goToPage: 'Go to page',
      clear: 'Clear',
      keywordSearch: 'Keyword Search',
      registerAsProvider: 'Register as provider',
      providerName: 'Name of provider',
      cancel: 'Cancel',
      send: 'Send',
      save: 'Save',
      preview: 'Preview',
      fillAllFields: 'Please fill in all the fields',
      contactProvider: 'Contact a provider',
    },
  },
  fr: {
    message: {
      home: 'Accueil',
      admin: 'Administrateur',
      provider: 'Prestataire',
      providers: 'Prestataires',
      activity: 'Activité',
      seeMap: 'Voir la carte',
      goToPage: 'Voir la page',
      clear: 'Effacer',
      keywordSearch: 'Recherche par mot-clé',
      registerAsProvider: "S'enregistrer en tant que prestataire",
      providerName: 'Nom du prestataire',
      cancel: 'Annuler',
      send: 'Envoyer',
      save: 'Sauvegarder',
      preview: 'Aperçu',
      fillAllFields: 'Veuillez remplir tous les champs',
      contactProvider: ' Contacter un prestataire',
    },
  },
}

export { messages }
